name: Django on Docker application

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose up -d
    - name: Django test
      run: docker exec django_travis_app /bin/ash -c "cd django_travis && python manage.py test"