name: Django on Docker application

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Django test
      run: docker run -v $PWD/:/inveted_folder python:3.7.3-alpine3.10 /bin/ash -c "ls"